In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
data = pd.read_csv('Loan payments data.csv')

In [3]:
data

,Loan_ID,loan_status,Principal,terms,effective_date,due_date,paid_off_time,past_due_days,age,education,Gender
0,xqd20166231,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/14/2016 19:31,NaN,45,High School or Below,male
1,xqd20168902,PAIDOFF,1000,30,9/8/2016,10/7/2016,10/7/2016 9:00,NaN,50,Bechalor,female
2,xqd20160003,PAIDOFF,1000,30,9/8/2016,10/7/2016,9/25/2016 16:58,NaN,33,Bechalor,female
3,xqd20160004,PAIDOFF,1000,15,9/8/2016,9/22/2016,9/22/2016 20:00,NaN,27,college,male
4,xqd20160005,PAIDOFF,1000,30,9/9/2016,10/8/2016,9/23/2016 21:36,NaN,28,college,female
5,xqd20160706,PAIDOFF,300,7,9/9/2016,9/15/2016,9/9/2016 13:45,NaN,35,Master or Above,male
6,xqd20160007,PAIDOFF,1000,30,9/9/2016,10/8/2016,10/7/2016 23:07,NaN,29,college,male
7,xqd20160008,PAIDOFF,1000,30,9/9/2016,10/8/2016,10/5/2016 20:33,NaN,36,college,male
8,xqd20160909,PAIDOFF,1000,30,9/9/2016,10/8/2016,10/8/2016 16:00,NaN,28,college,male
9,xqd20160010,PAIDOFF,800,15,9/10/2016,9/24/2016,9/24/2016 13:00,NaN,26,college,male
10,xqd20160011,PAIDOFF,300,7,9/10/2016,9/16/2016,9/11/2016 19:11,NaN,29,college,male
11,xqd20160012,PAIDOFF,1000,15,9/10/2016,10/9/2016,10/9/2016 16:00,NaN,39,High School or Below,male
12,xqd20160013,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/7/2016 23:32,NaN,26,college,male
13,xqd20160014,PAIDOFF,900,7,9/10/2016,9/16/2016,9/13/2016 21:57,NaN,26,college,female
14,xqd20160015,PAIDOFF,1000,7,9/10/2016,9/16/2016,9/15/2016 14:27,NaN,27,High School or Below,male
15,xqd20160016,PAIDOFF,800,15,9/10/2016,9/24/2016,9/24/2016 16:00,NaN,26,college,male
16,xqd20160017,PAIDOFF,1000,30,9/10/2016,10/9/2016,9/27/2016 14:21,NaN,40,High School or Below,male
17,xqd20160018,PAIDOFF,1000,15,9/10/2016,9/24/2016,9/23/2016 18:49,NaN,32,High School or Below,male
18,xqd20160019,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/5/2016 22:05,NaN,32,High School or Below,male
19,xqd20160020,PAIDOFF,800,30,9/10/2016,10/9/2016,9/23/2016 7:42,NaN,26,college,male
20,xqd20160021,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/9/2016 9:00,NaN,26,college,male
21,xqd20160022,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/8/2016 17:09,NaN,43,High School or Below,female
22,xqd20160023,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/9/2016 23:00,NaN,25,High School or Below,male
23,xqd20160024,PAIDOFF,1000,15,9/10/2016,9/24/2016,9/24/2016 13:00,NaN,26,college,male
24,xqd20160025,PAIDOFF,1000,30,9/10/2016,10/9/2016,10/3/2016 12:50,NaN,26,college,male
25,xqd20160026,PAIDOFF,1000,30,9/10/2016,10/9/2016,9/29/2016 12:18,NaN,29,High School or Below,male
26,xqd20160027,PAIDOFF,800,15,9/10/2016,9/24/2016,9/21/2016 20:16,NaN,39,Bechalor,male
27,xqd20170088,PAIDOFF,1000,15,9/10/2016,9/24/2016,9/23/2016 8:21,NaN,34,Bechalor,male
28,xqd20160029,PAIDOFF,1000,30,9/11/2016,10/10/2016,9/22/2016 19:17,NaN,31,college,male
29,xqd20160030,PAIDOFF,1000,30,9/11/2016,10/10/2016,10/9/2016 17:33,NaN,33,college,male
...,...,...,...,...,...,...,...,...,...,...,...
470,xqd20160471,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,9/28/2016 15:02,2.0,32,High School or Below,male
471,xqd20160472,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,11/4/2016 14:46,24.0,27,Bechalor,male
472,xqd20160473,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,11/16/2016 12:12,51.0,33,college,male
473,xqd20160474,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/14/2016 19:02,3.0,30,High School or Below,male
474,xqd20160475,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,9/28/2016 11:34,2.0,26,High School or Below,female
475,xqd20160476,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,11/9/2016 18:12,29.0,35,college,female
476,xqd20160477,COLLECTION_PAIDOFF,800,15,9/12/2016,10/26/2016,10/31/2016 13:07,5.0,46,college,female
477,xqd20160478,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/20/2016 17:38,9.0,27,college,male
478,xqd20160479,COLLECTION_PAIDOFF,1000,15,9/12/2016,10/11/2016,11/7/2016 8:55,27.0,22,High School or Below,male
479,xqd20160480,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/12/2016 18:26,1.0,27,Bechalor,male
480,xqd20160481,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,10/25/2016 13:44,29.0,30,Bechalor,male
481,xqd20160482,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,9/29/2016 15:07,3.0,27,High School or Below,male
482,xqd20160483,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,9/27/2016 11:40,1.0,47,college,male
483,xqd20160484,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/18/2016 19:08,7.0,30,college,male
484,xqd20160485,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/15/2016 9:23,4.0,26,college,male
485,xqd20160486,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/14/2016 10:07,3.0,38,High School or Below,male
486,xqd20160487,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,11/21/2016 11:36,56.0,46,High School or Below,male
487,xqd20160488,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/13/2016 12:02,2.0,35,Bechalor,male
488,xqd20160489,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,10/9/2016 19:30,13.0,45,college,male
489,xqd20160490,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/12/2016 18:04,1.0,36,college,male
490,xqd20160491,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/17/2016 10:53,6.0,38,High School or Below,male
491,xqd20160492,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,11/9/2016 13:41,29.0,27,college,male
492,xqd20160493,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/25/2016 17:44,14.0,27,Bechalor,male
493,xqd20160494,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,9/29/2016 12:45,3.0,29,college,male
494,xqd20160495,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/13/2016 14:45,2.0,30,High School or Below,male
495,xqd20160496,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/14/2016 19:08,3.0,28,High School or Below,male
496,xqd20160497,COLLECTION_PAIDOFF,1000,15,9/12/2016,9/26/2016,10/10/2016 20:02,14.0,26,High School or Below,male
497,xqd20160498,COLLECTION_PAIDOFF,800,15,9/12/2016,9/26/2016,9/29/2016 11:49,3.0,30,college,male
498,xqd20160499,COLLECTION_PAIDOFF,1000,30,9/12/2016,11/10/2016,11/11/2016 22:40,1.0,38,college,female
499,xqd20160500,COLLECTION_PAIDOFF,1000,30,9/12/2016,10/11/2016,10/19/2016 11:58,8.0,28,High School or Below,male

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
Loan_ID           500 non-null object
loan_status       500 non-null object
Principal         500 non-null int64
terms             500 non-null int64
effective_date    500 non-null object
due_date          500 non-null object
paid_off_time     400 non-null object
past_due_days     200 non-null float64
age               500 non-null int64
education         500 non-null object
Gender            500 non-null object
dtypes: float64(1), int64(3), object(7)
memory usage: 43.0+ KB

In [5]:
data['loan_status'].unique()

array(['PAIDOFF', 'COLLECTION', 'COLLECTION_PAIDOFF'], dtype=object)

In [6]:
data.isna().sum()

Loan_ID             0
loan_status         0
Principal           0
terms               0
effective_date      0
due_date            0
paid_off_time     100
past_due_days     300
age                 0
education           0
Gender              0
dtype: int64

In [7]:
{column: len(data[column].unique()) for column in data.columns}

{'Loan_ID': 500,
 'loan_status': 3,
 'Principal': 6,
 'terms': 3,
 'effective_date': 7,
 'due_date': 25,
 'paid_off_time': 321,
 'past_due_days': 34,
 'age': 33,
 'education': 4,
 'Gender': 2}

In [8]:
def binary_encode(df, column, positive_value):
    df = df.copy()
    df[column] = df[column].apply(lambda x: 1 if x == positive_value else 0)
    return df

def ordinal_encode(df, column, ordering):
    df = df.copy()
    df[column] = df[column].apply(lambda x: ordering.index(x))
    return df

In [9]:
def preprocess_inputs(df):
    df = df.copy()
    
    # 刪除 Loan_ID 欄位
    df = df.drop('Loan_ID', axis=1)
    
    # 新增日期欄位(月/日/小時)
    for column in ['effective_date', 'due_date', 'paid_off_time']:
        df[column] = pd.to_datetime(df[column])
    
    df['effective_day'] = df['effective_date'].apply(lambda x: x.day)
    
    df['due_month'] = df['due_date'].apply(lambda x: x.month)
    df['due_day'] = df['due_date'].apply(lambda x: x.day)
    
    df['paid_off_month'] = df['paid_off_time'].apply(lambda x: x.month)
    df['paid_off_day'] = df['paid_off_time'].apply(lambda x: x.day)
    df['paid_off_hour'] = df['paid_off_time'].apply(lambda x: x.hour)
    
    df = df.drop(['effective_date', 'due_date', 'paid_off_time'], axis=1)
    
    # 利用欄位平均值填補缺失值
    for column in ['past_due_days', 'paid_off_month', 'paid_off_day', 'paid_off_hour']:
        df[column] = df[column].fillna(df[column].mean())
    
    # 對性別欄位二元編碼
    df = binary_encode(df, 'Gender', positive_value='male')
    
    # 對教育欄位順序編碼
    education_ordering = [
        'High School or Below',
        'college',
        'Bechalor',
        'Master or Above'
    ]
    df = ordinal_encode(df, 'education', ordering=education_ordering)
    
    # 對label欄位編碼
    label_mapping = {'COLLECTION': 0, 'PAIDOFF': 1, 'COLLECTION_PAIDOFF': 2}
    df['loan_status'] = df['loan_status'].replace(label_mapping)
    
    # 將 df 劃分為 X 和 y 
    y = df['loan_status'].copy()
    X = df.drop('loan_status', axis=1).copy()
    
    # 將 X 標準化
    scaler = StandardScaler()
    X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
    
    return X, y

In [10]:
X, y = preprocess_inputs(data)

In [11]:
X

,Principal,terms,past_due_days,age,education,Gender,effective_day,due_month,due_day,paid_off_month,paid_off_day,paid_off_hour
0,0.493377,0.897891,0.000000,2.284043,-1.022825,0.426653,-3.126073,0.664986,-1.303142,-1.035098,-0.463997,1.339835
1,0.493377,0.897891,0.000000,3.106587,1.771779,-2.343823,-3.126073,0.664986,-1.303142,0.690066,-1.475829,-1.072109
2,0.493377,0.897891,0.000000,0.309935,1.771779,-2.343823,-3.126073,0.664986,-1.303142,-1.035098,1.126025,0.616252
3,0.493377,-0.978972,0.000000,-0.677119,0.374477,0.426653,-3.126073,-1.094236,0.724148,-1.035098,0.692382,1.581030
4,0.493377,0.897891,0.000000,-0.512610,0.374477,-2.343823,-2.209336,0.664986,-1.167989,-1.035098,0.836930,1.822224
5,-5.586972,-1.979965,0.000000,0.638953,3.169082,0.426653,-2.209336,-1.094236,-0.221921,-1.035098,-1.186734,-0.107332
6,0.493377,0.897891,0.000000,-0.348101,0.374477,0.426653,-2.209336,0.664986,-1.167989,0.690066,-1.475829,2.304613
7,0.493377,0.897891,0.000000,0.803462,0.374477,0.426653,-2.209336,0.664986,-1.167989,0.690066,-1.764924,1.581030
8,0.493377,0.897891,0.000000,-0.512610,0.374477,0.426653,-2.209336,0.664986,-1.167989,0.690066,-1.331282,0.616252
9,-1.243866,-0.978972,0.000000,-0.841628,0.374477,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.981477,-0.107332
10,-5.586972,-1.979965,0.000000,-0.348101,0.374477,0.426653,-1.292599,-1.094236,-0.086768,-1.035098,-0.897640,1.339835
11,0.493377,-0.978972,0.000000,1.296989,-1.022825,0.426653,-1.292599,0.664986,-1.032836,0.690066,-1.186734,0.616252
12,0.493377,0.897891,0.000000,-0.841628,0.374477,0.426653,-1.292599,0.664986,-1.032836,0.690066,-1.475829,2.304613
13,-0.375244,-1.979965,0.000000,-0.841628,0.374477,-2.343823,-1.292599,-1.094236,-0.086768,-1.035098,-0.608545,1.822224
14,0.493377,-1.979965,0.000000,-0.677119,-1.022825,0.426653,-1.292599,-1.094236,-0.086768,-1.035098,-0.319450,0.133863
15,-1.243866,-0.978972,0.000000,-0.841628,0.374477,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.981477,0.616252
16,0.493377,0.897891,0.000000,1.461498,-1.022825,0.426653,-1.292599,0.664986,-1.032836,-1.035098,1.415119,0.133863
17,0.493377,-0.978972,0.000000,0.145426,-1.022825,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.836930,1.098641
18,0.493377,0.897891,0.000000,0.145426,-1.022825,0.426653,-1.292599,0.664986,-1.032836,0.690066,-1.764924,2.063419
19,-1.243866,0.897891,0.000000,-0.841628,0.374477,0.426653,-1.292599,0.664986,-1.032836,-1.035098,0.836930,-1.554498
20,0.493377,0.897891,0.000000,-0.841628,0.374477,0.426653,-1.292599,0.664986,-1.032836,0.690066,-1.186734,-1.072109
21,0.493377,0.897891,0.000000,1.955025,-1.022825,-2.343823,-1.292599,0.664986,-1.032836,0.690066,-1.331282,0.857446
22,0.493377,0.897891,0.000000,-1.006137,-1.022825,0.426653,-1.292599,0.664986,-1.032836,0.690066,-1.186734,2.304613
23,0.493377,-0.978972,0.000000,-0.841628,0.374477,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.981477,-0.107332
24,0.493377,0.897891,0.000000,-0.841628,0.374477,0.426653,-1.292599,0.664986,-1.032836,0.690066,-2.054019,-0.348526
25,0.493377,0.897891,0.000000,-0.348101,-1.022825,0.426653,-1.292599,0.664986,-1.032836,-1.035098,1.704214,-0.348526
26,-1.243866,-0.978972,0.000000,1.296989,1.771779,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.547835,1.581030
27,0.493377,-0.978972,0.000000,0.474444,1.771779,0.426653,-1.292599,-1.094236,0.994453,-1.035098,0.836930,-1.313304
28,0.493377,0.897891,0.000000,-0.019083,0.374477,0.426653,-0.375862,0.664986,-0.897684,-1.035098,0.692382,1.339835
29,0.493377,0.897891,0.000000,0.309935,0.374477,0.426653,-0.375862,0.664986,-0.897684,0.690066,-1.186734,0.857446
...,...,...,...,...,...,...,...,...,...,...,...,...
470,0.493377,-0.978972,-1.834849,0.145426,-1.022825,0.426653,0.540875,-1.094236,1.264758,-1.035098,1.559667,0.375057
471,0.493377,0.897891,-0.647943,-0.677119,1.771779,0.426653,0.540875,0.664986,-0.762531,2.415229,-1.909472,0.133863
472,-1.243866,-0.978972,0.808715,0.309935,0.374477,0.426653,0.540875,-1.094236,1.264758,2.415229,-0.174902,-0.348526
473,0.493377,0.897891,-1.780899,-0.183592,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.463997,1.339835
474,-1.243866,-0.978972,-1.834849,-0.841628,-1.022825,-2.343823,0.540875,-1.094236,1.264758,-1.035098,1.559667,-0.589721
475,0.493377,0.897891,-0.378191,0.638953,0.374477,-2.343823,0.540875,0.664986,-0.762531,2.415229,-1.186734,1.098641
476,-1.243866,-0.978972,-1.672998,2.448552,0.374477,-2.343823,0.540875,0.664986,1.264758,0.690066,1.993309,-0.107332
477,0.493377,0.897891,-1.457197,-0.677119,0.374477,0.426653,0.540875,0.664986,-0.762531,0.690066,0.403287,0.857446
478,0.493377,-0.978972,-0.486092,-1.499664,-1.022825,0.426653,0.540875,0.664986,-0.762531,2.415229,-1.475829,-1.313304
479,0.493377,0.897891,-1.888799,-0.677119,1.771779,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.753092,1.098641
480,0.493377,-0.978972,-0.378191,-0.183592,1.771779,0.426653,0.540875,-1.094236,1.264758,0.690066,1.126025,-0.107332
481,0.493377,-0.978972,-1.780899,-0.677119,-1.022825,0.426653,0.540875,-1.094236,1.264758,-1.035098,1.704214,0.375057
482,-1.243866,-0.978972,-1.888799,2.613060,0.374477,0.426653,0.540875,-1.094236,1.264758,-1.035098,1.415119,-0.589721
483,0.493377,0.897891,-1.565098,-0.183592,0.374477,0.426653,0.540875,0.664986,-0.762531,0.690066,0.114192,1.339835
484,0.493377,0.897891,-1.726948,-0.841628,0.374477,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.319450,-1.072109
485,0.493377,0.897891,-1.780899,1.132480,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.463997,-0.830915
486,-1.243866,-0.978972,1.078466,2.448552,-1.022825,0.426653,0.540875,-1.094236,1.264758,2.415229,0.547835,-0.589721
487,0.493377,0.897891,-1.834849,0.638953,1.771779,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.608545,-0.348526
488,0.493377,-0.978972,-1.241396,2.284043,0.374477,0.426653,0.540875,-1.094236,1.264758,0.690066,-1.186734,1.339835
489,0.493377,0.897891,-1.888799,0.803462,0.374477,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.753092,1.098641
490,0.493377,0.897891,-1.619048,1.132480,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.030355,-0.830915
491,0.493377,0.897891,-0.378191,-0.677119,0.374477,0.426653,0.540875,0.664986,-0.762531,2.415229,-1.186734,-0.107332
492,0.493377,0.897891,-1.187446,-0.677119,1.771779,0.426653,0.540875,0.664986,-0.762531,0.690066,1.126025,0.857446
493,0.493377,-0.978972,-1.780899,-0.348101,0.374477,0.426653,0.540875,-1.094236,1.264758,-1.035098,1.704214,-0.348526
494,0.493377,0.897891,-1.834849,-0.183592,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.608545,0.133863
495,0.493377,0.897891,-1.780899,-0.512610,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,-0.463997,1.339835
496,0.493377,-0.978972,-1.187446,-0.841628,-1.022825,0.426653,0.540875,-1.094236,1.264758,0.690066,-1.042187,1.581030
497,-1.243866,-0.978972,-1.780899,-0.183592,0.374477,0.426653,0.540875,-1.094236,1.264758,-1.035098,1.704214,-0.589721
498,0.493377,0.897891,-1.888799,1.132480,0.374477,-2.343823,0.540875,2.424209,-0.897684,2.415229,-0.897640,2.063419
499,0.493377,0.897891,-1.511147,-0.512610,-1.022825,0.426653,0.540875,0.664986,-0.762531,0.690066,0.258740,-0.589721

In [12]:
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
470    2
471    2
472    2
473    2
474    2
475    2
476    2
477    2
478    2
479    2
480    2
481    2
482    2
483    2
484    2
485    2
486    2
487    2
488    2
489    2
490    2
491    2
492    2
493    2
494    2
495    2
496    2
497    2
498    2
499    2
Name: loan_status, Length: 500, dtype: int64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=150)

In [14]:
models = [
    LogisticRegression(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
]

for model in models:
    model.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [15]:
model_names = [
    "   Logistic Regression", 
    "         Decision Tree",
    "         Random Forest"
]

for model, name in zip(models, model_names):
    print(name + ": {:.4f}%".format(model.score(X_test, y_test) * 100))

   Logistic Regression: 97.3333%
         Decision Tree: 100.0000%
         Random Forest: 98.0000%